-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Mutation exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.ScalarCodecs
import API.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateUserRequiredArguments =
    { input : API.InputObject.NewUser }


{-|

  - input -

-}
create_user :
    CreateUserRequiredArguments
    -> SelectionSet decodesTo API.Object.User
    -> SelectionSet decodesTo RootMutation
create_user requiredArgs____ object____ =
    Object.selectionForCompositeField "create_user" [ Argument.required "input" requiredArgs____.input API.InputObject.encodeNewUser ] object____ Basics.identity


type alias CreateTaskRequiredArguments =
    { input : API.InputObject.NewTask }


{-|

  - input -

-}
create_task :
    CreateTaskRequiredArguments
    -> SelectionSet decodesTo API.Object.Task
    -> SelectionSet decodesTo RootMutation
create_task requiredArgs____ object____ =
    Object.selectionForCompositeField "create_task" [ Argument.required "input" requiredArgs____.input API.InputObject.encodeNewTask ] object____ Basics.identity
