-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Object exposing (..)


type Error
    = Error


type Job
    = Job


type Task
    = Task


type Token
    = Token


type User
    = User
