-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Query exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.ScalarCodecs
import API.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


{-| -}
list_tasks :
    SelectionSet decodesTo API.Object.Task
    -> SelectionSet (Maybe (List (Maybe decodesTo))) RootQuery
list_tasks object____ =
    Object.selectionForCompositeField "list_tasks" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


type alias LoginRequiredArguments =
    { id : String
    , pwd : String
    }


{-|

  - id -
  - pwd -

-}
login :
    LoginRequiredArguments
    -> SelectionSet decodesTo API.Union.LoginRes
    -> SelectionSet decodesTo RootQuery
login requiredArgs____ object____ =
    Object.selectionForCompositeField "login" [ Argument.required "id" requiredArgs____.id Encode.string, Argument.required "pwd" requiredArgs____.pwd Encode.string ] object____ Basics.identity
