-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Object.Job exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.ScalarCodecs
import API.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
docker_image : SelectionSet String API.Object.Job
docker_image =
    Object.selectionForField "String" "docker_image" [] Decode.string


{-| -}
dataset : SelectionSet (Maybe String) API.Object.Job
dataset =
    Object.selectionForField "(Maybe String)" "dataset" [] (Decode.string |> Decode.nullable)


{-| -}
env : SelectionSet (Maybe (List String)) API.Object.Job
env =
    Object.selectionForField "(Maybe (List String))" "env" [] (Decode.string |> Decode.list |> Decode.nullable)
